// Compact translucent banner; the game image keeps its original size.
import fs from 'node:fs';import path from 'node:path';import {spawn,execFileSync} from 'node:child_process';import {once} from 'node:events';import {createCanvas,registerFont} from 'canvas';
registerFont('/System/Library/Fonts/Menlo.ttc',{family:'Banner'});
const run=process.argv[2],dir=path.resolve('runs',run),source=path.join(dir,'full-playthrough.mp4'),out=path.join(dir,'full-playthrough-banner.mp4');
const events=fs.readFileSync(path.join(dir,'events.jsonl'),'utf8').trim().split('\n').map(JSON.parse),zero=Date.parse(events.find(e=>e.type==='recording_started').time),timeline=events.map(e=>({...e,at:(Date.parse(e.time)-zero)/1000})).sort((a,b)=>a.at-b.at);const startState=events.find(e=>e.type==='start')?.state,config=fs.existsSync(path.join(dir,'run-config.json'))?JSON.parse(fs.readFileSync(path.join(dir,'run-config.json'))):{planner:startState?.plannerModel||'qwen3.8-27b',controller:startState?.controllerModel||'jevk5-4b-v0.3'};const planner=String(config.planner||'qwen3.8-27b').split('/').at(-1),controller=String(config.controller||'jevk5-4b-v0.3').split('/').at(-1);const canvas=createCanvas(960,78),g=canvas.getContext('2d');let i=0,objective='Waiting for plan',action='Waiting for action',done=false,position=null;
function fit(s,width){s=String(s).replace(/[\r\n]+/g,' ');if(g.measureText(s).width<=width)return s;while(s.length&&g.measureText(s+'…').width>width)s=s.slice(0,-1);return s+'…';}
function draw(t){while(i<timeline.length&&timeline[i].at<=t){const e=timeline[i++];if(['position_sample','display_state','result'].includes(e.type)&&e.position)position=e.position;if(e.type==='plan')objective=e.result.objective;if(e.type==='decision'){const q=e.response?.answers?.action?.choice;action=e.request.questions.action.criteria[q]||e.selected;}if(e.type==='game_won'){done=true;action='Dragon defeated. Exit portal reached.';}}
 g.clearRect(0,0,960,78);g.fillStyle='rgba(8,20,28,0.64)';g.fillRect(0,0,960,78);g.textBaseline='top';g.font='bold 14px Banner';g.fillStyle='#f3f8fc';const ms=Math.round(t*1000),clock=String(Math.floor(ms/60000)).padStart(2,'0')+':'+String(Math.floor(ms/1000)%60).padStart(2,'0')+'.'+String(ms%1000).padStart(3,'0');const xyz=position?['x','y','z'].map(k=>Number(position[k]).toFixed(1)).join(' / '):'-- / -- / --';g.fillText(`${planner} + ${controller}  |  ${clock}  |  XYZ ${xyz}${done?'  |  COMPLETE':''}`,12,8);g.font='12px Banner';g.fillStyle='#e4edf5';g.fillText(fit(`${planner}: ${objective}`,936),12,33);g.fillStyle='#ffe3a2';g.fillText(fit(`${controller}: ${action}`,936),12,55);return canvas;}
if(process.argv[3]){const t=Number(process.argv[3]);draw(t);const frame=path.join(dir,'banner-layer.png');fs.writeFileSync(frame,canvas.toBuffer('image/png'));execFileSync('ffmpeg',['-y','-v','error','-ss',String(t),'-i',source,'-i',frame,'-filter_complex','[0:v][1:v]overlay=0:0','-frames:v','1',path.join(dir,'banner-preview.png')]);console.log(path.join(dir,'banner-preview.png'));process.exit();}
const media=JSON.parse(execFileSync('ffprobe',['-v','error','-show_entries','format=duration','-of','json',source],{encoding:'utf8'})),duration=Number(media.format.duration),band=path.join(dir,'translucent-banner.mov');const enc=spawn('ffmpeg',['-y','-v','error','-f','rawvideo','-pixel_format','bgra','-video_size','960x78','-framerate','20','-i','pipe:0','-an','-c:v','qtrle',band],{stdio:['pipe','ignore','inherit']});const ended=once(enc,'close');for(let n=0;n<Math.ceil(duration*20)+1;n++)if(!enc.stdin.write(draw(n/20).toBuffer('raw')))await once(enc.stdin,'drain');enc.stdin.end();if((await ended)[0]!==0)throw Error('Banner encode failed');execFileSync('ffmpeg',['-y','-v','error','-i',source,'-i',band,'-filter_complex','[0:v][1:v]overlay=0:0:repeatlast=1','-t',String(duration),'-r','20','-an','-c:v','libx264','-preset','veryfast','-crf','26','-pix_fmt','yuv420p','-movflags','+faststart',out],{stdio:'inherit'});fs.writeFileSync(path.join(dir,'banner-manifest.json'),JSON.stringify({source:path.basename(source),output:path.basename(out),durationSeconds:duration,width:960,height:540,opacity:.64,fullWidth:true,font:'Menlo',clockPrecision:'milliseconds at source 20 fps',coordinateSamplesHz:10,fields:['models','elapsed milliseconds','coordinates','planner objective','controller action'],timeMapping:'Unchanged source video time'},null,2));console.log(out);
