import {liningRecoveryActions} from './lining-recovery.mjs';
import {barterDefenseActions} from './covered-barter.mjs';
import {fortressStepCost} from './fortress-platform.mjs';
import {droppedItem} from './item-observation.mjs';
import {workGold,goldWorkActions} from './bastion-gold.mjs';
import {nightActions,recoverNightBed} from './night-safety.mjs';
import {shaftDefenseActions,openShaftWindow,coveredWalk,coveredDescent,coveredRise} from './covered-shaft.mjs';
import {overworldTravelActions} from './overworld-travel.mjs';
import {installBreathReflex} from './breath-reflex.mjs';
import {descendColumn} from './column-travel.mjs';
import {travelActions} from './nether-travel.mjs';
import {workshopActions} from './nether-workshop.mjs';
import {spareToolsReady} from './mining-tools.mjs';
import {defenseActions,threats} from './hostile-defense.mjs';
import {preparationActions,foodCount} from './eyes-preparation.mjs';
import {ingredientActions,fillEndPortalActions,foodActions,resistanceActions,hasFireResistanceSupply,barterTargets,neededIngredientDrop,unneededInventoryItems,eyeNeeds,suppliesObservation,equipSupplyArmor} from './nether-supplies.mjs';
import {installGroundSafety,groundStepCost} from './ground-safety.mjs';
import {supportedBreathMargin,breathStepCost} from './breath-safety.mjs';
import {selectUsefulOptions} from './optimization/policy.mjs';
import {installCursorSync,recoverCursor} from './inventory-recovery.mjs';
import {toolRecovery} from './tool-recovery.mjs';
import {installInventoryDisplay} from './inventory-display.mjs';
import mineflayer from 'mineflayer';import pf from 'mineflayer-pathfinder';import {Vec3} from 'vec3';import fs from 'node:fs';import http from 'node:http';
import {route,vec,kitNeeds,bedCount,portalActions,placeAt,solid} from './nether-route.mjs';import {installCameraControl} from './camera-control.mjs';import {installNativeMirror} from './native-mirror.mjs';import {startNativeRecording} from './native-record.mjs';import {decide,plan,plannerModel,plannerName,controllerModel,controllerName} from './models.mjs';import {endCombatActions} from './end-combat.mjs';import {battleObservation,updateDragonSensor} from './extra-actions.mjs';import {dragonDeathState,gameWon} from './evidence.mjs';
const {pathfinder,Movements,goals}=pf,run=process.env.RUN_ID||'nether-practice-01',dir='runs/'+run;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/pid',String(process.pid));
const bot=mineflayer.createBot({host:'127.0.0.1',port:Number(process.env.MC_PORT||25576),username:process.env.MC_USERNAME||'JevAstra',version:'1.16.5',respawn:false,checkTimeoutInterval:120000});bot.loadPlugin(pathfinder);const mirror=process.env.NATIVE_VIEW==='1'?installNativeMirror(bot):null;
let display;let portalObserved=false;
let stopped=false,steps=0,active='connecting',currentPlan=null,lastPlanAt=0,lastPlanStage=null,errors=0,won=false,dragonKilled=false,netherVisited=false,netherExited=false,prepared=false,finishNative=null,recordReady=false,recordFinished=false;let netherEntry=null;const saved=fs.existsSync(dir+'/status.json')?JSON.parse(fs.readFileSync(dir+'/status.json')):{};steps=saved.steps||0;netherEntry=saved.netherEntry||null;netherVisited=!!saved.netherVisited;netherExited=!!saved.netherExited;prepared=!!saved.prepared;let last=saved.recent||[],looted=new Set(saved.looted||[]),failed=new Map();
const log=(type,data={})=>fs.appendFileSync(dir+'/events.jsonl',JSON.stringify({time:new Date().toISOString(),type,...data})+'\n');
bot.on('physicsTick',()=>{if(bot.game.dimension==='the_end'||!bot.pathfinder.goal)return;const threat=threats(bot)[0];if(threat&&threat.position.distanceTo(bot.entity.position)<8){bot.navigationThreat=threat.id;bot.pathfinder.setGoal(null);bot.clearControlStates();log('travel_hostile_stop',{entity:threat.id,name:threat.name,position:bot.entity.position});}});
bot.on('bedBlastAttempt',data=>log('bed_blast_attempt',data));
bot.goldWork=saved.goldWork||null;bot.goldBatchReady=!!saved.goldBatchReady;
const travel=saved.travel||{region:'entry',leg:null,index:0};
const inventory=()=>{const i={};for(const q of bot.inventory.slots.slice(5).filter(Boolean))i[q.name]=(i[q.name]||0)+q.count;return i;};const item=n=>bot.inventory.items().find(i=>i.name===n);const pos=p=>p?{x:+p.x.toFixed(2),y:+p.y.toFixed(2),z:+p.z.toFixed(2)}:null;
function stage(){if(won)return 'complete';if(dragonKilled)return 'exit';if(bot.game.dimension==='the_end')return 'combat';if(bot.game.dimension==='the_nether')return 'nether';if(netherExited)return 'stronghold';if(prepared)return 'entry';return 'prepare';}
function state(){return {run,travel,goldBatchReady:bot.goldBatchReady,goldWork:bot.goldWork,observedGoldBlocks:bot.observedGoldBlocks||[],observedGoldOre:bot.observedGoldOre||[],steps,active,prepared,looted:[...looted],stage:stage(),position:pos(bot.entity?.position),dimension:bot.game.dimension,localTerrain:bot.entity?Object.fromEntries([['floor',-1],['feet',0],['head',1],['ceiling',2]].map(([name,y])=>[name,bot.blockAt(bot.entity.position.floored().offset(0,y,0))?.name])):null,health:bot.health,food:bot.food,inventory:inventory(),cursorItem:bot.inventory.selectedItem?{name:bot.inventory.selectedItem.name,count:bot.inventory.selectedItem.count}:null,tools:bot.inventory.items().filter(i=>i.name.endsWith('_pickaxe')).map(i=>({name:i.name,damage:i.durabilityUsed})),supplies:suppliesObservation(bot),eyeNeeds:eyeNeeds(inventory(),route.missingEyes),barterTargets:barterTargets(bot,eyeNeeds(inventory(),route.missingEyes)),netherEntry,kitNeeds:{...kitNeeds(inventory()),netherAxe:inventory().stone_axe||inventory().iron_axe||inventory().diamond_axe?0:1,reserveCobblestone:Math.max(0,48-(inventory().cobblestone||0)),spareStonePicks:Math.max(0,3-(inventory().stone_pickaxe||0)),spareSticks:Math.max(0,16-(inventory().stick||0)),sparePlanks:Math.max(0,64-Object.entries(inventory()).filter(([n])=>n.endsWith('_planks')).reduce((n,[,v])=>n+v,0))},netherVisited,netherExited,difficulty:bot.game.difficulty,knownSeed:{...route,netherRoute:route.netherRoute,remainingChests:route.chests.filter(p=>!looted.has(vec(p).toString()))},plan:currentPlan,recent:last.slice(-8),battle:bot.entity?battleObservation(bot):null,won,dragonKilled,recordReady,recordFinished,plannerModel,plannerName,controllerModel,controllerName};}
const sensor=setInterval(async()=>{if(!process.env.DRAGON_SENSOR_URL)return;try{updateDragonSensor(await (await fetch(process.env.DRAGON_SENSOR_URL,{signal:AbortSignal.timeout(500)})).json());}catch{}},50);
const statusTimer=setInterval(()=>{if(bot.entity)fs.writeFileSync(dir+'/status.json',JSON.stringify(state(),null,2));},2000);const displayTimer=setInterval(()=>{if(bot.entity&&recordReady&&!recordFinished)log('display_state',state());},1000);
http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(state()));}).listen(Number(process.env.STATUS_PORT||3078),'127.0.0.1');
bot.on('nativeCameraTurn',data=>{if(recordReady&&!recordFinished)log('native_camera_turn',data);});
bot.on('physicsTick',()=>{if(bot.game.dimension==='the_end'){const margin=supportedBreathMargin(bot,bot.entity.position,Object.values(bot.entities).filter(e=>e.name==='area_effect_cloud'));bot.emergencyTravelStop=margin<2;if(bot.emergencyTravelStop&&(bot.checkedTravelActive||bot.pathfinder.isMoving())){bot.pathfinder.setGoal(null);bot.stopDigging();bot.clearControlStates();}}});
bot.on('entityDead',e=>{if(e.name==='blaze')log('blaze_killed',{entity:e.id,position:pos(e.position)});if(e.name==='piglin_brute')log('brute_killed',{entity:e.id,position:pos(e.position)});});
bot.on('error',e=>log('error',{error:e.message}));bot.on('kicked',e=>{stopped=true;log('kicked',{reason:e});});bot.on('end',()=>{stopped=true;});bot.on('death',()=>{log('death',{state:state()});stopped=true;active='Player died; run stopped';});
bot.on('spawn',()=>{if(bot.game.dimension==='the_nether'){netherEntry||=pos(bot.entity.position);netherVisited=true;log('nether_entered',{position:pos(bot.entity.position)});}else if(netherVisited&&bot.game.dimension==='overworld'&&!won&&!stopped){netherExited=true;log('nether_exited',{position:pos(bot.entity.position),inventory:inventory(),needs:eyeNeeds(inventory(),route.missingEyes)});}});
bot._client.on('game_state_change',packet=>{if(gameWon(packet)&&dragonKilled){won=true;active='Dragon defeated. Exit portal reached.';log('game_won',{packet,dragonKilled});fs.writeFileSync(dir+'/victory.json',JSON.stringify({run,time:new Date().toISOString(),won,dragonKilled,state:state()},null,2));}});
async function bounded(promise,ms=15000){let t;try{return await Promise.race([promise,new Promise((_,reject)=>{t=setTimeout(()=>{bot.pathfinder.setGoal(null);bot.clearControlStates();bot.stopDigging();reject(Error('Action timeout'));},ms);})]);}finally{clearTimeout(t);}}
async function go(p,range=2,ms=15000){if(bot.entity.position.distanceTo(p.offset(.5,0,.5))<range+.3)return;const start=bot.entity.position.clone();try{await bounded(bot.pathfinder.goto(new goals.GoalNear(p.x,p.y,p.z,range)),ms);}finally{bot.pathfinder.setGoal(null);bot.clearControlStates();}if(bot.entity.position.distanceTo(p.offset(.5,0,.5))>range+1)throw Error('Path stopped before target; moved '+bot.entity.position.distanceTo(start).toFixed(1));}
async function segment(q){if(Math.hypot(q.x-bot.entity.position.x,q.z-bot.entity.position.z)<1)return go(q,2,15000);const p=bot.entity.position,d=Math.hypot(q.x-p.x,q.z-p.z),n=Math.min(24,d);const x=Math.round(p.x+(q.x-p.x)/d*n),z=Math.round(p.z+(q.z-p.z)/d*n);try{await bounded(bot.pathfinder.goto(new goals.GoalXZ(x,z)),12000);}finally{bot.pathfinder.setGoal(null);bot.clearControlStates();}return 'Moved one approach segment';}
async function mine(q){if(bot.game.dimension==='the_nether'&&['gold_block','nether_gold_ore'].includes(bot.blockAt(q)?.name))return workGold(bot,q,log);if(Math.hypot(bot.entity.position.x-q.x,bot.entity.position.z-q.z)>28)return segment(q);await go(q,bot.blockAt(q)?.name.endsWith('_bed')?1:3);bot.pathfinder.setGoal(null);bot.clearControlStates();const b=bot.blockAt(q),t=b.name.endsWith('_bed')?null:bot.pathfinder.bestHarvestTool(b);if(t)await bot.equip(t,'hand');if(b.name!=='air'&&b.name!=='cave_air')await bot.dig(b,true);await bot.waitForTicks(4);const drop=Object.values(bot.entities).filter(e=>e.name==='item'&&e.position.distanceTo(q)<3).sort((a,b)=>a.position.distanceTo(bot.entity.position)-b.position.distanceTo(bot.entity.position))[0];if(drop)await go(drop.position,.6,15000);await bot.waitForTicks(4);return 'Mined and approached drop: '+b.name;}
function candidates(){const out=[],add=(key,description,fn)=>{if((failed.get(key)||0)<Date.now())out.push({key,description,fn});},s=stage(),i=inventory(),p=bot.entity.position;
 bot.fortressCombatActive=s==='nether'&&travel.region==='fortress'&&eyeNeeds(i,route.missingEyes).rods>0;
 if(bot.breathReflexActive){add('continue_breath_escape','Continue the selected movement skill while its immediate breath escape completes',()=>bot.waitForTicks(5));return out;}
 if(s==='combat'||s==='exit'){if(bot.health<16&&bot.food<20&&supportedBreathMargin(bot,p,Object.values(bot.entities).filter(e=>e.name==='area_effect_cloud'))>3){foodActions(bot,add,{item});if(out.length)return out;}endCombatActions(bot,add,{go,bounded,item});if(supportedBreathMargin(bot,p,Object.values(bot.entities).filter(e=>e.name==='area_effect_cloud'))>3&&bot.food<20)foodActions(bot,add,{item});return out;}
 if(barterDefenseActions(bot,add,log))return out;
 if(shaftDefenseActions(bot,add,log))return out;
 if(s==='nether'&&travel.region==='fortress'){
  resistanceActions(bot,add,{fortress:route.fortress});if(out.length)return out;
  const needs=eyeNeeds(i,route.missingEyes);
  if(needs.rods===0&&needs.pearls===0&&p.y<90){bot.deactivateItem();if(travelActions(bot,add,travel,'entry',{go,mine,log}))return out;}
 }

 const coveredBastion=s==='nether'&&p.x>=-140&&p.x<=-110&&p.z>=32&&p.z<=50&&p.y>=83&&p.y<=96;
 if(!coveredBastion){defenseActions(bot,add,{item,log});if(threats(bot).some(e=>e.position.distanceTo(p)<(e.name==='piglin_brute'?12:4)))return out;}
 if(bot.defenseBase&&!threats(bot).length){const guardedEnemy=bot.entities[bot.defenseHandledThreat];if(guardedEnemy&&guardedEnemy.metadata?.[8]>0&&guardedEnemy.position.distanceTo(p)<32){add('wait_guarded_enemy','Wait on the defense pillar while the observed brute approaches',()=>bot.waitForTicks(20));return out;}if(p.y>bot.defenseBase.y+.1){add('leave_defense_pillar','Return to the checked floor after defeating nearby enemies',async()=>{await descendColumn(bot,bot.defenseBase.y,log);if(bot.entity.position.y<=bot.defenseBase.y+.1)bot.defenseBase=null;});return out;}bot.defenseBase=null;}
 if(nightActions(bot,add,{go,item}))return out.filter(a=>['sleep_night','place_night_bed','prepare_night_bed'].includes(a.key));if(recoverNightBed(bot,add,{mine,go}))return out;
 foodActions(bot,add,{item});if((bot.food<16||bot.health<16)&&out.some(a=>a.key.startsWith('eat_')))return out.filter(a=>a.key.startsWith('eat_'));
 if(bot.game.dimension==='the_nether'&&bot.health<16&&bot.food>=18){add('recover_health','Hold the shield and wait three seconds for health to recover before travel or combat',async()=>{bot.pathfinder.setGoal(null);bot.clearControlStates();const e=Object.values(bot.entities).filter(e=>['blaze','piglin_brute','wither_skeleton','skeleton','hoglin'].includes(e.name)).sort((a,b)=>a.position.distanceTo(bot.entity.position)-b.position.distanceTo(bot.entity.position))[0];if(e)await bot.lookAt(e.position.offset(0,1,0));if(bot.inventory.slots[45]?.name==='shield')bot.activateItem(true);await bot.waitForTicks(60);});return out.filter(a=>a.key==='recover_health');}
 bot.netherTransit=bot.game.dimension==='the_nether'&&!!travel.leg;
 const junk=unneededInventoryItems(bot);if(bot.inventory.emptySlotCount()<4&&junk.length&&Date.now()-(bot.lastInventoryTidy||0)>45000){add('tidy_inventory','Discard unneeded stone variants and barter by-products to make room for essential supplies',async()=>{bot.lastInventoryTidy=Date.now();for(const q of junk.slice(0,6))await bot.tossStack(q);});return out;}
 if(bot.inventory.emptySlotCount()<4&&(i.netherrack||0)>320&&Date.now()-(bot.lastBlockTrim||0)>45000){add('trim_netherrack','Keep four stacks of netherrack for protected routes and discard excess in one batch',()=>{bot.lastBlockTrim=Date.now();return bot.toss(bot.registry.itemsByName.netherrack.id,null,(inventory().netherrack||0)-256);});return out;}
 if(liningRecoveryActions(bot,add,log))return out;
 ingredientActions(bot,add,{go,mine,item,inventory,missingEyes:route.missingEyes,fortress:route.fortress,log});
 const essentialVisible=Object.values(bot.entities).some(e=>e.name==='item'&&e.position.distanceTo(p)<12&&['ender_pearl','potion','splash_potion'].includes(droppedItem(e)?.name)&&neededIngredientDrop(bot,droppedItem(e),eyeNeeds(i,route.missingEyes)));
 if(essentialVisible||out.some(a=>a.key.startsWith('essential_drop_')))return out.filter(a=>a.key.startsWith('essential_drop_')||a.key.startsWith('eat_'));
 const needsGold=eyeNeeds(i,route.missingEyes),barterNeeded=needsGold.pearls>0||needsGold.rods>0&&!hasFireResistanceSupply(bot,needsGold.rods>=3?2:1);if(goldWorkActions(bot,add,log,{needed:barterNeeded}))return out.filter(a=>['continue_protected_gold','finish_gold_batch'].includes(a.key)||a.key.startsWith('eat_'));
 if(out.some(a=>a.key==='wait_piglin_ready'))return out.filter(a=>a.key==='wait_piglin_ready'||a.key.startsWith('ingredient_drop_')||a.key.startsWith('eat_'));
 if(s==='prepare'){
  preparationActions(bot,add,{go,mine,item,inventory,route});if(out.some(a=>a.key==='gather_shaft_lining')&&i.iron_pickaxe&&i.shield&&spareToolsReady(i)&&bedCount(i)>=8&&foodCount(i)>=12)return out.filter(a=>a.key==='gather_shaft_lining'||a.key.startsWith('eat_'));if(out.some(a=>a.key==='return_for_wood'))return out.filter(a=>a.key==='return_for_wood'||a.key.startsWith('eat_'));
  if(foodCount(i)<16&&!i.hay_block&&(i.wheat||0)<3&&route.foodPoint&&p.distanceTo(vec(route.foodPoint))>12)add('approach_hay','Travel to the surveyed hay patch at '+vec(route.foodPoint)+' to make the required bread',()=>Math.hypot(p.x-route.foodPoint.x,p.z-route.foodPoint.z)>28?segment(vec(route.foodPoint)):go(vec(route.foodPoint),3));
  for(const e of Object.values(bot.entities).filter(e=>e.name==='item'&&droppedItem(e)?.name.endsWith('_bed')).sort((a,b)=>a.position.distanceTo(p)-b.position.distanceTo(p)).slice(0,2))if(bedCount(i)<8)add('pickup_'+e.id,'Collect dropped '+droppedItem(e)?.name+' at '+e.position.floored()+'; distance '+Math.round(e.position.distanceTo(p)),async()=>{if(e.position.distanceTo(bot.entity.position)>28)return segment(e.position);await go(e.position,.6,15000);await bot.waitForTicks(4);return 'Approached dropped bed';});
  if(out.some(a=>a.key.startsWith('pickup_')))return out.filter(a=>a.key.startsWith('pickup_')); // Collect dropped beds before they expire.
  for(const q of route.chests.map(vec).filter(q=>!looted.has(q.toString())&&(q.y>40||i.iron_pickaxe&&i.shield&&i.crafting_table&&spareToolsReady(i)&&bedCount(i)>=8&&((i.bread||0)>=12))))add('chest_'+q,'Loot surveyed supply chest at '+q+'; distance '+Math.round(q.distanceTo(p)),async()=>{if(Math.hypot(bot.entity.position.x-q.x,bot.entity.position.z-q.z)>28)return segment(q);if(q.y<40&&bot.entity.position.y>q.y+3.1){if(Math.hypot(bot.entity.position.x-q.x-.5,bot.entity.position.z-q.z-.5)>.8){await bounded(bot.pathfinder.goto(new goals.GoalXZ(q.x,q.z)),12000);return 'Reached the covered chest descent column';}bot.portalDescentStarted=true;return coveredDescent(bot,q.y+3,log);}const before=bot.entity.position.clone();try{await go(q,3);}catch(e){if(bot.entity.position.distanceTo(before)>2)return 'Made progress toward the chest';throw e;}const chest=bot.blockAt(q);if(chest?.name!=='chest')throw Error('Chest not loaded');const c=await bot.openContainer(chest);await display.chestOpened();try{for(const t of c.containerItems())if(!['rotten_flesh','poisonous_potato','music_disc_13','saddle','map','filled_map','paper','compass','bone','gunpowder','enchanted_book'].includes(t.name))await c.withdraw(t.type,t.metadata,t.count);}finally{await display.chestClosing();c.close();}looted.add(q.toString());return 'Looted chest';});
  if(i.iron_ingot&&i.flint&&!i.flint_and_steel){const recipe=bot.recipesFor(bot.registry.itemsByName.flint_and_steel.id,null,1,null)[0];if(recipe)add('craft_ignition','Craft one flint and steel from carried iron and flint',()=>bot.craft(recipe,1,null));}
  if((i.iron_pickaxe||i.stone_pickaxe)&&bedCount(i)<8)for(const q of bot.findBlocks({matching:b=>b.name.endsWith('_bed')&&b.getProperties().part==='head',maxDistance:128,count:4}))add('bed_'+q,'Collect village bed at '+q+'; have '+bedCount(i)+' of 8',()=>mine(q));
  if(looted.size>=route.chests.length&&i.iron_pickaxe&&(i.cobblestone||0)+(i.dirt||0)<32){for(const q of bot.findBlocks({matching:b=>['stone','cobblestone','dirt'].includes(b.name),maxDistance:10,count:100}).filter(q=>Math.abs(q.y-p.y)<3&&!(q.x===Math.floor(p.x)&&q.z===Math.floor(p.z))).sort((a,b)=>(a.y<Math.floor(p.y)?20:0)-(b.y<Math.floor(p.y)?20:0)+a.distanceTo(p)-b.distanceTo(p)).slice(0,2))add('blocks_'+q,'Mine one navigation block at '+q+'; need '+kitNeeds(i).navigationBlocks+' more',()=>mine(q));}
  if(i.iron_pickaxe&&i.shield&&bedCount(i)>=8&&foodCount(i)>=12&&spareToolsReady(i)&&!i.crafting_table){const table=bot.findBlock({matching:bot.registry.blocksByName.crafting_table.id,maxDistance:24});if(table)add('pack_crafting_table','Collect the crafting table now that the required tools and bread are complete',()=>mine(table.position));}
  if(Object.values(kitNeeds(i)).every(n=>n===0)&&spareToolsReady(i))add('depart','Preparation complete. Enter the Nether to obtain ingredients for the missing Eyes of Ender.',async()=>{await display.review();const table=bot.findBlock({matching:bot.registry.blocksByName.crafting_table.id,maxDistance:12});if(!item('crafting_table')&&table)await mine(table.position);prepared=true;return 'Kit complete';});
 }
 if(s==='entry')portalActions(bot,add,route.entryPortal,{go,bounded,item,segment},'entry');
 if(s==='nether'){
  equipSupplyArmor(bot,add);
  const needs=eyeNeeds(i,route.missingEyes);
  if(workshopActions(bot,add,{inventory,mine,go}))return out.filter(a=>a.key.startsWith('workshop_')||a.key.startsWith('eat_'));
  if(out.some(a=>a.key==='drink_fire_resistance'))return out.filter(a=>a.key==='drink_fire_resistance');
  if(travelActions(bot,add,travel,(needs.pearls>0||needs.rods>0&&!hasFireResistanceSupply(bot,needs.rods>=3?2:1))?'bastion':needs.rods>0?'fortress':'entry',{go,mine,log}))return out.filter(a=>!a.key.startsWith('bastion_')&&!a.key.startsWith('mine_gold_')&&!a.key.startsWith('barter_')&&!a.key.startsWith('approach_blaze_')); 
  for(const q of route.bastionChests.map(vec).filter(q=>!looted.has('nether:'+q.toString())&&(!bot.blockAt(q)||bot.blockAt(q).name==='chest')))if(p.distanceTo(q)<30&&Math.abs(p.y-q.y)<8&&(!(i.gold_ingot||i.gold_block)&&eyeNeeds(i,route.missingEyes).pearls>0||bot.food<12))add('bastion_chest_'+q,'Loot the surveyed bastion chest at '+q+' for gold, food and armor; piglins may become hostile',async()=>{const safeY=q.y+3;if(p.y<safeY-.1)return coveredRise(bot,safeY,log);if(p.y>safeY+.1)return coveredDescent(bot,safeY,log);if(Math.hypot(p.x-q.x,p.z-q.z)>2.5)return coveredWalk(bot,new Vec3(q.x,safeY,q.z),log);const dx=Math.abs(q.x-p.x)>=Math.abs(q.z-p.z)?Math.sign(q.x-p.x):0,dz=dx?0:Math.sign(q.z-p.z);await openShaftWindow(bot,dx,dz);for(const dx of [-1,0,1]){const base=bot.blockAt(q.offset(dx,0,0)),lid=bot.blockAt(q.offset(dx,1,0));if(base?.name==='chest'&&lid?.boundingBox==='block'&&lid.diggable){if(bot.entity.position.floored().offset(0,-1,0).equals(lid.position))return coveredWalk(bot,new Vec3(q.x+2,safeY,q.z),log);bot.pathfinder.setGoal(null);bot.clearControlStates();const tool=bot.pathfinder.bestHarvestTool(lid);if(tool)await bot.equip(tool,'hand');await bot.dig(lid,true);}}bot.clearControlStates();await bot.waitForTicks(2);const c=await bot.openContainer(bot.blockAt(q));try{for(const t of c.containerItems())if(['gold_ingot','gold_block','iron_block','iron_ingot','golden_carrot','cooked_porkchop','diamond_leggings','golden_leggings','golden_boots','obsidian','arrow','spectral_arrow','crossbow'].includes(t.name))await c.withdraw(t.type,t.metadata,t.count);}finally{c.close();}looted.add('nether:'+q.toString());});
  if(needs.pearls>0){const target=vec(route.bastion);if(travel.region!=='bastion'&&p.distanceTo(target)>12)add('bastion_approach','Approach the surveyed bastion to obtain gold and barter for '+needs.pearls+' pearls',()=>go(target,3,15000));}
  else if(needs.rods>0){const target=vec(route.fortress);if(p.distanceTo(target)>8)add('fortress_approach','Approach the surveyed blaze spawner to obtain '+needs.rods+' more blaze rods',()=>go(target,3,15000));else add('wait_blaze_spawn','Wait two seconds near the natural blaze spawner for an observed blaze',()=>bot.waitForTicks(40));}
  else {const target=netherEntry?vec(netherEntry):vec(route.netherEntry);if(p.distanceTo(target)>8)add('return_entry_portal','Return to the original Nether portal with the collected Eye ingredients',()=>go(target,2,15000));else{const portal=bot.findBlock({matching:bot.registry.blocksByName.nether_portal.id,maxDistance:16});if(portal)add('return_overworld','Enter the original portal and return to the Overworld',async()=>{await go(portal.position,0,10000);bot.clearControlStates();for(let n=0;n<140&&bot.game.dimension==='the_nether';n++)await bot.waitForTicks(1);});}}
 }
 if(s==='stronghold'){
  if(workshopActions(bot,add,{inventory,mine,go}))return out.filter(a=>a.key.startsWith('workshop_')||a.key.startsWith('eat_'));
  if(overworldTravelActions(bot,add,{bounded,log}))return out;
  const target=vec(route.activePortal),stand=vec(route.strongholdStand);
  if(Math.hypot(p.x-stand.x-.5,p.z-stand.z-.5)<3&&p.y>stand.y+1){add('stronghold_checked_descent','Descend through a covered shaft to the surveyed portal room floor',()=>coveredDescent(bot,stand.y,log));return out;}
  if(!portalObserved){const frames=bot.findBlocks({matching:bot.registry.blocksByName.end_portal_frame.id,maxDistance:32,count:12}).map(q=>bot.blockAt(q));if(frames.length===12){portalObserved=true;log('portal_initial_observation',{frames:frames.map(b=>({position:b.position,eye:b.getProperties().eye})),active:!!bot.findBlock({matching:bot.registry.blocksByName.end_portal.id,maxDistance:32})});}}
  if(portalObserved)fillEndPortalActions(bot,add,{go,item,log});
  if(bot.findBlock({matching:bot.registry.blocksByName.end_portal_frame.id,maxDistance:16})&&!bot.findBlock({matching:bot.registry.blocksByName.end_portal.id,maxDistance:16})){if(!out.length)add('inspect_portal','Wait for the portal and inventory observations',()=>bot.waitForTicks(10));return out;}
  if(Math.hypot(p.x-target.x-.5,p.z-target.z-.5)<4&&p.y>=target.y&&p.y-target.y<6){add('enter_end_careful','Step over the observed active End portal; remove one blocking floor block only when the portal is directly below',async()=>{const start=bot.entity.position.clone(),dx=target.x+.5-start.x,dz=target.z+.5-start.z;if(Math.hypot(dx,dz)>.12){await bot.lookAt(new Vec3(target.x+.5,start.y+1.62,target.z+.5),true);bot.setControlState('forward',true);try{for(let n=0;n<12;n++){await bot.waitForTicks(1);if(bot.game.dimension==='the_end'||Math.hypot(bot.entity.position.x-target.x-.5,bot.entity.position.z-target.z-.5)<.1)break;}}finally{bot.clearControlStates();}}else{const q=bot.entity.position.floored().offset(0,-1,0),b=bot.blockAt(q),column=[1,2,3].map(n=>bot.blockAt(q.offset(0,-n,0)));if(b?.diggable&&column.find(c=>c&&(c.name==='end_portal'||c.name==='lava'||c.boundingBox==='block'))?.name==='end_portal'){const pick=item('iron_pickaxe')||item('stone_pickaxe');if(pick)await bot.equip(pick,'hand');await bot.dig(b,true);}await bot.waitForTicks(12);}return 'Checked portal entry step';});return out;}
  add('stronghold_approach','Travel toward the surveyed incomplete End portal room at '+target,async()=>{const before=bot.entity.position.clone();try{if(Math.hypot(p.x-target.x,p.z-target.z)>32)await segment(target);else await go(bot.findBlock({matching:bot.registry.blocksByName.end_portal.id,maxDistance:24})?target:vec(route.strongholdStand),0,15000);}catch(e){if(bot.entity.position.distanceTo(before)<2)throw e;return 'Made stronghold approach progress';}});
 }
 if(!out.length)add('wait','Wait one second for game updates',()=>bot.waitForTicks(20));return out;
}
async function main(){bot.waitAwayForPerch=true;const preparedPause=fs.existsSync(dir+'/paused');if(preparedPause)bot.physicsEnabled=false;while(fs.existsSync(dir+'/paused'))await new Promise(r=>setTimeout(r,100));installCursorSync(bot,log);installCameraControl(bot,log);installBreathReflex(bot,log);installGroundSafety(bot,log);display=installInventoryDisplay(bot,log,!!mirror);await bot.waitForChunksToLoad().catch(e=>{if(!bot.blockAt(bot.entity.position.floored().offset(0,-1,0)))throw e;log('partial_chunk_load',{reason:e.message});});if(preparedPause){bot.physicsEnabled=true;await bot.waitForTicks(5);}const moves=new Movements(bot);moves.allowParkour=false;moves.maxDropDown=3;moves.liquidCost=20;moves.allow1by1towers=true;moves.scafoldingBlocks=[bot.registry.itemsByName.dirt.id,bot.registry.itemsByName.netherrack.id,bot.registry.itemsByName.blackstone.id,bot.registry.itemsByName.polished_blackstone_bricks.id];moves.exclusionAreasPlace.push(b=>bot.blockAt(b.position.offset(0,-1,0))?.name==='chest'?100:0);moves.exclusionAreasBreak.push(b=>bot.game.dimension==='the_nether'&&['nether_brick_fence','spawner'].includes(b.name)?100:0);moves.exclusionAreasBreak.push(b=>{for(let x=-1;x<=1;x++)for(let y=0;y<=1;y++)for(let z=-1;z<=1;z++)if(bot.blockAt(b.position.offset(x,y,z))?.name==='lava')return 100;return 0;});moves.exclusionAreasStep.push(b=>groundStepCost(bot,b));moves.exclusionAreasStep.push(b=>bot.game.dimension==='overworld'&&bot.surfaceTargetHeight!=null&&b.position.y<bot.surfaceTargetHeight-4?100:0);moves.exclusionAreasStep.push(b=>fortressStepCost(bot,b,route.fortress));moves.exclusionAreasStep.push(b=>bot.game.dimension==='the_nether'&&Object.values(bot.entities).some(e=>e.name==='piglin_brute'&&e.metadata?.[8]>0&&Math.hypot(e.position.x-b.position.x,e.position.z-b.position.z)<5&&Math.abs(e.position.y-b.position.y)<2)?100:0);moves.exclusionAreasStep.push(b=>bot.game.dimension==='the_end'?breathStepCost(b,Object.values(bot.entities).filter(e=>e.name==='area_effect_cloud')):0);bot.pathfinder.setMovements(moves);bot.pathfinder.thinkTimeout=2500;
 if(mirror&&process.env.WAIT_NATIVE==='1'){active='Waiting for hidden native client';while(!mirror.ready)await new Promise(r=>setTimeout(r,250));}if(process.env.NATIVE_RECORD==='1'){finishNative=await startNativeRecording(dir,log);recordReady=true;}
 log('start',{seed:route.seed,version:bot.version,difficulty:bot.game.difficulty,state:state()});
 while(!stopped&&!won){
  while(stage()==='entry'&&fs.existsSync(dir+'/pause-entry'))await new Promise(r=>setTimeout(r,250));
  if(fs.existsSync(dir+'/stop')){log('development_trial_ended',{reason:fs.readFileSync(dir+'/stop','utf8')});break;}
  if(mirror&&recordReady&&!mirror.captureHealthy){log('capture_wait',{reason:'Waiting for recorder heartbeat before next action'});const deadline=Date.now()+30000;while(!mirror.captureHealthy&&Date.now()<deadline)await new Promise(r=>setTimeout(r,250));if(!mirror.captureHealthy){log('capture_failure',{reason:'Native recorder heartbeat did not recover'});break;}log('capture_resumed',{});}
  const battle=battleObservation(bot);if(!dragonKilled&&dragonDeathState(battle)){dragonKilled=true;log('dragon_killed',{source:'server entity health zero and dying phase',battle});}
  let opts=selectUsefulOptions(candidates());if(!opts.length)opts=[{key:'refresh_observation',description:'Wait one second for a fresh observation after a blocked action',fn:()=>bot.waitForTicks(20)}];const s=state();if(!currentPlan||lastPlanStage!==s.stage||Date.now()-lastPlanAt>120000||errors>=2&&Date.now()-lastPlanAt>10000){active=plannerName+' planning';try{const r=await plan({...s,availableActions:opts.map(o=>o.description)});currentPlan=r.result;log('plan',r);lastPlanStage=s.stage;lastPlanAt=Date.now();console.log('PLAN',JSON.stringify(currentPlan));}catch(e){log('plan_error',{error:e.message});throw e;}}
  active=controllerName+' decision';const r=await decide(state(),opts);if(won||stopped)break;active=r.selected.description;log('decision',{step:steps,model:r.model,request:r.body,response:r.data,latencyMs:r.latencyMs,selected:r.selected.key});console.log('ACTION',steps,active);
  let result;try{result=await bounded(r.selected.fn(),25000);errors=0;}catch(e){result='FAILED '+e.message;failed.set(r.selected.key,Date.now()+3000);errors++;try{await bot._syncWindow(bot.currentWindow||bot.inventory);await recoverCursor(bot);}catch(sync){log('inventory_sync_error',{error:sync.message});}}
  steps++;const row={step:steps,action:active,result:typeof result==='string'?result:'done',position:pos(bot.entity.position),inventory:inventory()};last.push(row);last=last.slice(-20);log('result',row);console.log('RESULT',row.result);
 }
 bot.pathfinder.setGoal(null);bot.clearControlStates();if(won){active='Dragon defeated. Exit portal reached.';await new Promise(r=>setTimeout(r,6000));}if(finishNative){await finishNative();recordFinished=true;}fs.writeFileSync(dir+'/status.json',JSON.stringify(state(),null,2));
}
bot.once('spawn',()=>main().catch(async e=>{log('fatal',{error:e.stack});console.error(e);if(finishNative)await finishNative();stopped=true;}));
process.on('SIGINT',async()=>{stopped=true;bot.pathfinder.setGoal(null);bot.clearControlStates();if(finishNative)await finishNative();bot.quit();process.exit(0);});
