apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minecraft-agent-staging
  labels:
    app.kubernetes.io/part-of: minecraft-agent
spec:
  secretName: minecraft-agent-tls-staging
  dnsNames:
    - minecraft-agent.omv.mousses.xyz
  issuerRef:
    name: letsencrypt-staging-cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
