package local.agentview;
import java.nio.*;import java.nio.file.*;import java.io.*;import java.lang.reflect.Field;import java.awt.image.BufferedImage;import javax.imageio.ImageIO;import java.util.concurrent.*;import org.lwjgl.glfw.GLFW;import org.lwjgl.opengl.GL11;import org.lwjgl.opengl.GL30;import org.lwjgl.system.MemoryUtil;
public class FrameCapture {
 static long last=0,lastPreview=0,lastHeartbeat=0,lastPoll=0,startNanos=0,frames=0,nextReadyCheck=0;static ByteBuffer pixels;static int width,height;static volatile boolean busy=false,readinessReported=false,readinessLookupErrorReported=false;static int readinessProbeState=-1;static String requested="",recording="";static Process encoder;static OutputStream pipe;static Object minecraft;static Field activeLevel,modelManager,modelGroups;
 static final Path root=Paths.get(System.getProperty("agent.captureDir"));
 static final ExecutorService writer=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"native-frame-writer");t.setDaemon(true);return t;});
 static void finish(){try{if(pipe!=null){pipe.close();if(!encoder.waitFor(30,TimeUnit.SECONDS)){encoder.destroyForcibly();encoder.waitFor();}Files.writeString(Paths.get(recording+".finished.json"),"{\"time\":\""+java.time.Instant.now()+"\",\"frames\":"+frames+",\"fps\":20,\"exitCode\":"+encoder.exitValue()+"}");}}catch(Exception e){e.printStackTrace();}finally{pipe=null;encoder=null;recording="";}}
 // Mojang's 1.16.5 mappings name these fields djz.r=level, djz.aw=modelManager, and elt.h=modelGroups.
 static void checkResourcesReady(){if(readinessReported)return;long now=System.nanoTime();if(now<nextReadyCheck)return;nextReadyCheck=now+250_000_000L;try{if(minecraft==null){Class<?> type=Class.forName("djz");minecraft=type.getMethod("C").invoke(null);activeLevel=type.getDeclaredField("r");activeLevel.setAccessible(true);modelManager=type.getDeclaredField("aw");modelManager.setAccessible(true);}if(activeLevel.get(minecraft)==null)return;Object models=modelManager.get(minecraft);if(models==null){logReadinessProbe(0);return;}if(modelGroups==null){modelGroups=models.getClass().getDeclaredField("h");modelGroups.setAccessible(true);}boolean ready=modelGroups.get(models)!=null;logReadinessProbe(ready?2:1);if(ready)resourcesReady();}catch(Exception e){if(!readinessLookupErrorReported){readinessLookupErrorReported=true;System.err.println("Native client readiness check failed: "+e);}}}
 static void logReadinessProbe(int state){if(state!=readinessProbeState){readinessProbeState=state;String[] labels={"model manager unavailable","model groups loading","model groups ready"};System.out.println("Native client world active; "+labels[state]);}}
 public static void resourcesReady(){try{Files.writeString(root.resolve("resources-ready.txt"),java.time.Instant.now().toString());readinessReported=true;System.out.println("Native client resources ready in active world");}catch(Exception e){e.printStackTrace();}}
 public static void frame(long window){
  local.agentview.NativeUi.tick();
  checkResourcesReady();
  long now=System.nanoTime();
  if(now-lastPoll>500_000_000L){lastPoll=now;try{Path control=root.resolve("record-path.txt");requested=Files.exists(control)?Files.readString(control).trim():"";}catch(Exception e){requested="";}}
  if(busy||now-last<(requested.isEmpty()?1_000_000_000L:45_000_000L))return;last=now;
  try{
   int[] vp=new int[4];GL11.glGetIntegerv(GL11.GL_VIEWPORT,vp);int w=vp[2],h=vp[3];if(w<1||h<1)return;
   if(pixels==null||width!=w||height!=h){if(pixels!=null)MemoryUtil.memFree(pixels);width=w;height=h;pixels=MemoryUtil.memAlloc(width*height*4);}
   int oldFramebuffer=GL11.glGetInteger(GL30.GL_READ_FRAMEBUFFER_BINDING);GL30.glBindFramebuffer(GL30.GL_READ_FRAMEBUFFER,0);GL11.glReadBuffer(GL11.GL_BACK);pixels.clear();GL11.glReadPixels(0,0,width,height,GL11.GL_RGBA,GL11.GL_UNSIGNED_BYTE,pixels);GL30.glBindFramebuffer(GL30.GL_READ_FRAMEBUFFER,oldFramebuffer);
   byte[] data=new byte[width*height*4];pixels.get(data);int ww=width,hh=height;String want=requested;boolean preview=now-lastPreview>2_000_000_000L;if(preview)lastPreview=now;busy=true;
   writer.submit(()->{try{
    if(!want.equals(recording)){finish();if(!want.isEmpty()){recording=want;Path output=Paths.get(want),live=output.getParent().resolve("native-live");Files.createDirectories(live);String hls=live.resolve("index.m3u8").toString();String tee="[f=mp4:movflags=+faststart]"+want+"|[f=hls:hls_time=2:hls_list_size=3:hls_flags=delete_segments+omit_endlist+independent_segments]"+hls;String ffmpeg=System.getProperty("agent.ffmpeg","ffmpeg");encoder=new ProcessBuilder(ffmpeg,"-y","-f","rawvideo","-pixel_format","rgba","-video_size","960x540","-framerate","20","-i","pipe:0","-vf","vflip","-an","-map","0:v:0","-c:v","libx264","-preset","veryfast","-threads","2","-g","40","-keyint_min","40","-sc_threshold","0","-crf","29","-maxrate","1600k","-bufsize","3200k","-pix_fmt","yuv420p","-f","tee",tee).redirectError(new File(want+".encoder.log")).redirectOutput(ProcessBuilder.Redirect.DISCARD).start();pipe=encoder.getOutputStream();startNanos=now;frames=0;Files.writeString(Paths.get(want+".started.json"),"{\"time\":\""+java.time.Instant.now()+"\",\"width\":960,\"height\":540,\"fps\":20,\"hls\":\"native-live/index.m3u8\"}");}}
    if(pipe!=null){byte[] frame=data;if(ww!=960||hh!=540){frame=new byte[960*540*4];for(int y=0;y<540;y++)for(int x=0;x<960;x++){int src=((y*hh/540)*ww+x*ww/960)*4,dst=(y*960+x)*4;frame[dst]=data[src];frame[dst+1]=data[src+1];frame[dst+2]=data[src+2];frame[dst+3]=data[src+3];}}long due=(now-startNanos)/50_000_000L+1;while(frames<due){pipe.write(frame);frames++;}}
    if(pipe!=null&&now-lastHeartbeat>1_000_000_000L){lastHeartbeat=now;Path dest=root.resolve("capture-heartbeat.json"),temp=root.resolve("capture-heartbeat.tmp.json");Files.writeString(temp,"{\"time\":"+System.currentTimeMillis()+",\"frames\":"+frames+",\"encoderAlive\":"+encoder.isAlive()+"}");Files.move(temp,dest,StandardCopyOption.REPLACE_EXISTING);}
    if(preview){BufferedImage image=new BufferedImage(ww,hh,BufferedImage.TYPE_INT_RGB);int[] rgb=new int[ww*hh];for(int y=0;y<hh;y++)for(int x=0;x<ww;x++){int i=((hh-1-y)*ww+x)*4;rgb[y*ww+x]=((data[i]&255)<<16)|((data[i+1]&255)<<8)|(data[i+2]&255);}image.setRGB(0,0,ww,hh,rgb,0,ww);Path dest=root.resolve("native-preview.png"),temp=root.resolve("native-preview.tmp.png");ImageIO.write(image,"png",temp.toFile());Files.move(temp,dest,StandardCopyOption.REPLACE_EXISTING);}
   }catch(Exception e){e.printStackTrace();finish();}finally{busy=false;}});
  }catch(Throwable e){e.printStackTrace();}
 }
}
